"""Windows lab setup helpers for the local research website and Nginx."""

from __future__ import annotations

import argparse
import json
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import urlparse

IGNORE_HREF_PREFIXES = ("mailto:", "tel:", "javascript:", "#")


class LinkParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.links: list[str] = []
        self.assets: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attr_map = dict(attrs)
        if tag == "a" and attr_map.get("href"):
            self.links.append(attr_map["href"] or "")
        elif tag in {"img", "script"} and attr_map.get("src"):
            self.assets.append(attr_map["src"] or "")
        elif tag == "link" and attr_map.get("href"):
            self.assets.append(attr_map["href"] or "")


def windows_nginx_path(path: Path) -> str:
    return path.resolve().as_posix()


def normalize_nginx_path(path: str) -> str:
    return path.replace("\\", "/")


def normalize_local_ref(ref: str) -> str | None:
    ref = ref.strip()
    if not ref or ref.startswith(IGNORE_HREF_PREFIXES):
        return None
    parsed = urlparse(ref)
    if parsed.scheme or parsed.netloc:
        return None
    return parsed.path or None


def _resolve_local_target(website_root: Path, html_file: Path, normalized: str) -> Path:
    if normalized.startswith("/"):
        return (website_root / normalized.lstrip("/")).resolve()
    return (html_file.parent / normalized).resolve()


def _safe_relative(base: Path, target: Path) -> str:
    try:
        return str(target.relative_to(base)).replace("\\", "/")
    except ValueError:
        return str(target).replace("\\", "/")


def check_website_links(project_root: Path) -> dict[str, object]:
    website_root = project_root / "website_lab"
    html_files = sorted(website_root.rglob("*.html"))
    missing_links: list[dict[str, str]] = []
    missing_assets: list[dict[str, str]] = []
    pages: list[dict[str, object]] = []

    for html_file in html_files:
        parser = LinkParser()
        parser.feed(html_file.read_text(encoding="utf-8"))
        page_record: dict[str, object] = {
            "page": _safe_relative(website_root, html_file),
            "links": [],
            "assets": [],
        }
        for href in parser.links:
            normalized = normalize_local_ref(href)
            if normalized is None:
                continue
            target = _resolve_local_target(website_root, html_file, normalized)
            exists = target.exists()
            rec = {"href": href, "target": _safe_relative(website_root, target), "exists": exists}
            cast_links = page_record["links"]
            assert isinstance(cast_links, list)
            cast_links.append(rec)
            if not exists:
                missing_links.append({"page": page_record["page"], "href": href})
        for src in parser.assets:
            normalized = normalize_local_ref(src)
            if normalized is None:
                continue
            target = _resolve_local_target(website_root, html_file, normalized)
            exists = target.exists()
            rec = {"src": src, "target": _safe_relative(website_root, target), "exists": exists}
            cast_assets = page_record["assets"]
            assert isinstance(cast_assets, list)
            cast_assets.append(rec)
            if not exists:
                missing_assets.append({"page": page_record["page"], "src": src})
        pages.append(page_record)

    return {
        "website_root": windows_nginx_path(website_root),
        "page_count": len(html_files),
        "missing_links": missing_links,
        "missing_assets": missing_assets,
        "pages": pages,
    }


def render_nginx_windows_conf(project_root: Path, *, port: int = 8039, access_log: str = 'logs/access.log', error_log: str = 'logs/error.log') -> str:
    website_root = windows_nginx_path(project_root / "website_lab")
    access_log = normalize_nginx_path(access_log)
    error_log = normalize_nginx_path(error_log)
    return f'''# Auto-generated by python -m wsd.lab_setup
worker_processes  1;
error_log   {error_log} warn;

events {{
    worker_connections  1024;
}}

http {{
    include       mime.types;
    default_type  application/octet-stream;

    log_format combined_custom '$remote_addr - $remote_user [$time_local] '
                               '"$request" $status $body_bytes_sent '
                               '"$http_referer" "$http_user_agent"';

    sendfile        on;
    keepalive_timeout  65;

    server {{
        listen       {port};
        server_name  localhost 127.0.0.1;

        access_log  {access_log}  combined_custom;
        root   {website_root};
        index  index.html;

        location / {{
            try_files $uri $uri/ /index.html;
        }}

        location = /healthz {{
            default_type text/plain;
            return 200 'ok';
        }}
    }}
}}
'''


def write_lab_artifacts(project_root: Path, *, port: int = 8039, output_dir: Path | None = None, access_log: str = 'logs/access.log', error_log: str = 'logs/error.log') -> dict[str, str]:
    project_root = project_root.resolve()
    output_dir = (output_dir or project_root / "lab" / "generated").resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    report_path = output_dir / "website_link_check.json"
    report_path.write_text(json.dumps(check_website_links(project_root), indent=2), encoding="utf-8")
    conf_path = output_dir / "nginx.conf"
    conf_path.write_text(render_nginx_windows_conf(project_root, port=port, access_log=access_log, error_log=error_log), encoding="utf-8")
    return {"conf_path": str(conf_path), "report_path": str(report_path)}


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Windows Nginx config and website consistency reports")
    parser.add_argument("--project-root", default=".", help="Project root containing website_lab/")
    parser.add_argument("--port", type=int, default=8039, help="Port for the local Nginx lab")
    parser.add_argument("--output-dir", default=None, help="Where to write generated config/report files")
    parser.add_argument("--write-conf", default=None, help="Optional explicit nginx.conf output path")
    parser.add_argument("--write-report", default=None, help="Optional explicit report output path")
    parser.add_argument("--access-log", default='logs/access.log', help="Nginx access log path to embed in nginx.conf")
    parser.add_argument("--error-log", default='logs/error.log', help="Nginx error log path to embed in nginx.conf")
    args = parser.parse_args()

    project_root = Path(args.project_root).resolve()
    output_dir = Path(args.output_dir).resolve() if args.output_dir else None
    paths = write_lab_artifacts(project_root, port=args.port, output_dir=output_dir, access_log=args.access_log, error_log=args.error_log)

    if args.write_conf:
        write_conf_path = Path(args.write_conf)
        write_conf_path.parent.mkdir(parents=True, exist_ok=True)
        write_conf_path.write_text(Path(paths["conf_path"]).read_text(encoding="utf-8"), encoding="utf-8")
    if args.write_report:
        write_report_path = Path(args.write_report)
        write_report_path.parent.mkdir(parents=True, exist_ok=True)
        write_report_path.write_text(Path(paths["report_path"]).read_text(encoding="utf-8"), encoding="utf-8")

    print(json.dumps(paths, indent=2))


if __name__ == "__main__":
    main()
